name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: MakeFile
      run: MakeFile
    - name: MakeFile check
      run: MakeFile check
    - name: MakeFile distcheck
      run: MakeFile distcheck
